# Form implementation generated from reading ui file 'gui3.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewMorganMoore3(object):
    def setupUi(self, NewMorganMoore3):
        NewMorganMoore3.setObjectName("NewMorganMoore3")
        NewMorganMoore3.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NewMorganMoore3.sizePolicy().hasHeightForWidth())
        NewMorganMoore3.setSizePolicy(sizePolicy)
        self.label_values = QtWidgets.QLabel(parent=NewMorganMoore3)
        self.label_values.setGeometry(QtCore.QRect(30, 30, 331, 41))
        self.label_values.setObjectName("label_values")
        self.label_op = QtWidgets.QLabel(parent=NewMorganMoore3)
        self.label_op.setGeometry(QtCore.QRect(30, 85, 331, 41))
        self.label_op.setObjectName("label_op")
        self.label_answer = QtWidgets.QLabel(parent=NewMorganMoore3)
        self.label_answer.setGeometry(QtCore.QRect(37, 145, 291, 61))
        self.label_answer.setObjectName("label_answer")
        self.input_values = QtWidgets.QLineEdit(parent=NewMorganMoore3)
        self.input_values.setGeometry(QtCore.QRect(90, 30, 251, 31))
        self.input_values.setObjectName("input_values")
        self.dropdown_op = QtWidgets.QComboBox(parent=NewMorganMoore3)
        self.dropdown_op.setGeometry(QtCore.QRect(90, 90, 251, 31))
        self.dropdown_op.setObjectName("dropdown_op")
        self.dropdown_op.addItem("")
        self.dropdown_op.addItem("")
        self.dropdown_op.addItem("")
        self.dropdown_op.addItem("")
        self.dropdown_op.addItem("")
        self.button_submit = QtWidgets.QPushButton(parent=NewMorganMoore3)
        self.button_submit.setGeometry(QtCore.QRect(150, 210, 100, 32))
        self.button_submit.setObjectName("button_submit")

        self.retranslateUi(NewMorganMoore3)
        QtCore.QMetaObject.connectSlotsByName(NewMorganMoore3)

    def retranslateUi(self, NewMorganMoore3):
        _translate = QtCore.QCoreApplication.translate
        NewMorganMoore3.setWindowTitle(_translate("NewMorganMoore3", "NewMorganMoore3"))
        self.label_values.setText(_translate("NewMorganMoore3", "Values: "))
        self.label_op.setText(_translate("NewMorganMoore3", "Operator: "))
        self.label_answer.setText(_translate("NewMorganMoore3", "Answer ="))
        self.dropdown_op.setItemText(0, _translate("NewMorganMoore3", "add"))
        self.dropdown_op.setItemText(1, _translate("NewMorganMoore3", "subtract"))
        self.dropdown_op.setItemText(2, _translate("NewMorganMoore3", "multiply"))
        self.dropdown_op.setItemText(3, _translate("NewMorganMoore3", "divide"))
        self.dropdown_op.setItemText(4, _translate("NewMorganMoore3", "choose"))
        self.button_submit.setText(_translate("NewMorganMoore3", "SUBMIT"))
